server:
  port: 5555
eureka:
  instance:
    prefer-ip-address: true
    instance-id: zuulservice
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
      organizationservice: /organization/**
      licensingservice: /licensing/**
  ignored-services: '*'
  prefix: /api
spring:
  application:
    name: zuulservice
hystrix:
  commond:
    default:
      execution:
        isolation:
          tread:
            timeoutInMilliseconds: 5000
ribbon:
  ReadTimeout: 5000
