example:
  property: "I AM IN THE DEFAULT"
spring:
  datasource:
    river-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my-oa?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
       ddl-auto: apdate
       dialect: org.hibernate.dialect.MySQL5Dialect
       naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy