#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/springboot
#spring.datasource.username=root
#spring.datasource.password=123456
#logging.level.org.springframework.security=trace
#spring.thymeleaf.cache=false
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.mvc.view.prefix=/templates/
#spring.mvc.view.suffix=.html
example:
  property: "I AM IN THE DEFAULT"
spring:
  datasource:
    river-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: {cipher}7140f25f4d3214590316f05d808a18f220b4ab7d72aebd37a8d384207d8575bb
  jpa:
    database: mysql
    show-sql: true
    hibernate:
       ddl-auto: update
       dialect: org.hibernate.dialect.MySQL5Dialect
       naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy